### ISSUE TITLE
What are the input population and frequency values?

### ISSUE THREAD

**Issue by yeemey** [robjohnnoble/ggmuller#11]
Hello,

I'm generating input dataframes for ggmuller, and am confused about where the values in the Population column are supposed to come from. I tried using variant allele frequencies at each generation, but the resulting plot is not what I expected. Based on the given example, it looks like the get_Muller_df function actually calculates and returns frequency values, instead of taking user-input frequencies?

Thanks for your help!

**Comment by robjohnnoble** [comment]
Hi,

The Population column contains data on the sizes of the types (either counts or frequencies). For example, take a look at the `example_pop_df` data frame that's included in the package.

If the format is still unclear then please either email me a sample of your data or paste some data in this thread, and explain what the data represent.

Rob.

**Comment by yeemey** [comment]
My data comprise 4 variants that consecutively sweep through the population. I used the variant frequencies at each Generation for the Population data. Here's the code I used to generate my data frames:
```
test_pop3 <- data.frame(Generation = rep(c(0,100,300,500,780,1000),4), 
                        Identity = c(rep("vt1",6), rep("vt2",6), rep("vt3",6), rep("vt4",6)), 
                        Population = c(0,7,100,100,100,100, 0,0,99,99,100,100, 0,0,0,59,99,100, 0,0,0,0,90,100))
test_edges3 <- data.frame(Parent = c("vt1", "vt2", "vt3"), 
                          Identity = c("vt2", "vt3", "vt4"))

test_Muller_df <- get_Muller_df(test_edges3, test_pop3)
Muller_plot(test_Muller_df, add_legend = TRUE, xlab = "Time", ylab = "Proportion")
```

This is the plot I get, which shows the correct parent/child relationship, but not the sweeps:
![image](https://user-images.githubusercontent.com/4806863/57389564-4f76b900-716f-11e9-9e36-93dd81feb43e.png)

**Comment by robjohnnoble** [comment]
Thanks for sharing the details.

First, I suggest dropping the first row of your population data frame, since all populations are zero at that time point, which cannot be plotted in a frequency diagram (hence the crooked left side of your plot). The data are then:
```
test_pop3 <- data.frame(Generation = rep(c(100,300,500,780,1000),4),
                         Identity = c(rep("vt1",5), rep("vt2",5), rep("vt3",5), rep("vt4",5)),
                         Population = c(7,100,100,100,100, 0,99,99,100,100, 0,0,59,99,100, 0,0,0,90,100))
```
Now, for a variant to achieve a selective sweep, it must have population size greater than zero at the same time as all other variants have population size zero. In your data this never happens for vt2, vt3 and vt4. The plot is consistent with the data.

**Comment by robjohnnoble** [comment]
You can see this also by just plotting the populations in a line plot:
```
library(ggplot2)
ggplot(test_pop3, aes(x = Generation, y = Population, group = Identity, col = Identity)) + geom_line()
```

**Comment by robjohnnoble** [comment]
OK, now I think I understand the issue. Your "Population" column contains variant allele frequencies, not genotype population sizes. Below is a complete solution. I've added "wt" (wild type) to represent the subpopulation with none of the mutations vt1-vt4, and I use the `diff` function to convert from VAF to Population.
```
test_pop3 <- data.frame(Generation = rep(c(0,100,300,500,780,1000),5),
                         Identity = c(rep("wt",6), rep("vt1",6), rep("vt2",6), rep("vt3",6), rep("vt4",6)),
                         VAF = c(100,100,100,100,100,100, 0,7,100,100,100,100, 0,0,99,99,100,100, 0,0,0,59,99,100, 0,0,0,0,90,100))
test_edges3 <- data.frame(Parent = c("wt", "vt1", "vt2", "vt3"),
                          Identity = c("vt1", "vt2", "vt3", "vt4"))
test_pop3$Population <- -diff(c(test_pop3$VAF, rep(0, 6)), 6)
test_Muller_df <- get_Muller_df(test_edges3, test_pop3)
Muller_plot(test_Muller_df, add_legend = TRUE, xlab = "Time", ylab = "Proportion")
```
![image](https://user-images.githubusercontent.com/6522653/57438444-3c81e880-7244-11e9-950b-d75544a2e0ba.png)

**Comment by yeemey** [comment]
Thank you! Converting to population sizes clarified it for me.
