### ISSUE TITLE
Can't get example to work

### ISSUE THREAD

**Issue by bensprung** [robjohnnoble/ggmuller#7]
Hi, I've installed ggmuller as suggested here https://thesefewlines.wordpress.com/2016/08/20/how-to-ggmuller/. However I get the following error:

```
> library(ggmuller)
> Muller_df <- get_Muller_df(example_edges, example_pop_df) >  
> Muller_plot(Muller_df) Error: All select() inputs must resolve to integer column positions. The following do not: *  colour_by
```

Any advice?

Thanks,
Ben

**Comment by robjohnnoble** [comment]
Hi Ben,
Sorry to hear that you've encountered a problem.
The code works fine on my machine and on other systems (according to CRAN tests). Since your error is generated by dplyr, I suspect the issue might be that you're using a version of dplyr that's somehow incompatible with some ggmuller code.
If your installed version of dplyr isn't the latest release version (v.0.7.4) then I suggest you install that version and try running the code again.
Please let me know whether this solves the problem.
Kind regards,
Rob.

**Comment by bensprung** [comment]
Hi Rob, thanks for the fast help. Updating dplyr did the trick!
Ben

**Comment by robjohnnoble** [comment]
Glad to hear it! Please could you tell me which version of dplyr produced the error? I might then add a note or a requirement to prevent the problem happening again.
Cheers.
Rob.

**Comment by bensprung** [comment]
Scrolling back, it looks like it was 0.5.0, because at one point I got this
error message.

> library(dplyr)Error in unloadNamespace(package) :
  namespace ‘dplyr’ is imported by ‘ggmuller’ so cannot be
unloadedError in library(dplyr) :
  Package ‘dplyr’ version 0.5.0 cannot be unloaded


The funny thing is that it looks like the original install of ggmuller
tried to install 0.7.4, but I guess it was unsuccessful:

> library(devtools)> install_github("robjohnnoble/ggmuller")Downloading GitHub repo robjohnnoble/ggmuller@master
from URL https://api.github.com/repos/robjohnnoble/ggmuller/zipball/masterInstalling
ggmullertrying URL
'https://cran.rstudio.com/src/contrib/dplyr_0.7.4.tar.gz'Content type
'unknown' length 808054 bytes (789
KB)==================================================downloaded 789 KB
Installing dplyrtrying URL
'https://cran.rstudio.com/src/contrib/BH_1.65.0-1.tar.gz'Content type
'unknown' length 10839577 bytes (10.3
MB)==================================================downloaded 10.3
MB

**Comment by robjohnnoble** [comment]
Thanks very much, Ben. I'll have a look into this.
Rob.

**Comment by bensprung** [comment]
No prob. Thanks for making ggmuller available
